services:
  - type: worker
    name: amazon-music-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: API_BASE
        sync: false
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: amzn_music_bot
      - key: LOG_CHANNEL
        value: "0"
      - key: DEV_URL
        sync: false
      - key: DEV_USERNAME
        sync: false
